import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test.setTimeout(60000)

async function chooseCalculator(page, id, label) {
  const mobile = page.getByRole('combobox', { name: 'Rechner wählen', exact: true })
  if (await mobile.isVisible()) await mobile.selectOption(id)
  else await page.getByRole('group', { name: 'Rechner wählen', exact: true }).getByRole('button', { name: label, exact: true }).click()
}

test('integrated aspect ratio, loan and BMI use real fields and preserve legacy links @matrix', async ({ page }) => {
  const requests = []
  page.on('request', request => requests.push({ url: request.url(), method: request.method(), body: request.postData() }))
  await page.goto('/workspace?tool=aspect-ratio')
  await expect(page).toHaveURL(/\/calculate\?calculator=aspect-ratio$/)
  await expect(page.getByRole('heading', { name: 'Weitere Rechner', exact: true })).toHaveCount(0)
  await page.getByRole('textbox', { name: 'Breite (px)', exact: true }).fill('1920')
  await page.getByRole('textbox', { name: 'Höhe (px)', exact: true }).fill('1080')
  await expect(page.getByTestId('result-ratio')).toHaveText('16:9')
  await page.getByRole('combobox', { name: 'Berechnung', exact: true }).selectOption('resize')
  await page.getByRole('textbox', { name: 'Zielbreite (px)', exact: true }).fill('1280')
  await expect(page.getByTestId('result-targetHeight')).toHaveText('720 px')

  await chooseCalculator(page, 'loan', 'Kreditrate')
  await page.getByRole('textbox', { name: 'Kreditbetrag', exact: true }).fill('10000')
  await page.getByRole('textbox', { name: 'Jahreszins (%)', exact: true }).fill('6')
  await page.getByRole('textbox', { name: 'Laufzeit (Monate)', exact: true }).fill('36')
  await expect(page.getByTestId('result-monthlyPayment')).toHaveText('304,22')
  await expect(page.getByTestId('result-totalPayment')).toHaveText('10951,90')
  await expect(page.getByTestId('result-totalInterest')).toHaveText('951,90')

  await chooseCalculator(page, 'bmi', 'BMI')
  await page.getByRole('textbox', { name: 'Gewicht (kg)', exact: true }).fill('70')
  await page.getByRole('textbox', { name: 'Grösse (cm)', exact: true }).fill('175')
  await expect(page.getByTestId('result-bmi')).toHaveText('22,86')
  await page.goBack()
  await expect(page.getByTestId('result-monthlyPayment')).toHaveText('304,22')
  await page.goForward()
  await expect(page.getByRole('textbox', { name: 'Gewicht (kg)', exact: true })).toHaveValue('70')
  const origin = new URL(page.url()).origin
  expect(requests.every(request => new URL(request.url).origin === origin && ['GET', 'HEAD'].includes(request.method) && !request.body)).toBe(true)
})

test('calculator fields solve everyday formulas and keep query history @matrix', async ({ page }) => {
  await page.goto('/workspace?tool=percentage-calc')
  await expect(page.getByRole('heading', { level: 1, name: 'Rechner' })).toBeVisible()
  await expect(page).toHaveURL(/\/calculate\?calculator=percent$/)
  await page.getByRole('textbox', { name: 'Prozentsatz', exact: true }).fill('12,5')
  await page.getByRole('textbox', { name: 'Grundwert', exact: true }).fill('240')
  await expect(page.getByTestId('result-result')).toHaveText('30')
  await page.getByRole('combobox', { name: 'Berechnung', exact: true }).selectOption('change')
  await page.getByLabel('Ausgangswert', { exact: true }).fill('80')
  await page.getByLabel('Neuer Wert', { exact: true }).fill('60')
  await expect(page.getByTestId('result-result')).toHaveText('-25 %')

  await chooseCalculator(page, 'rule-of-three', 'Dreisatz')
  await page.getByLabel('Wert A', { exact: true }).fill('3')
  await page.getByLabel('Entspricht B', { exact: true }).fill('12')
  await page.getByLabel('Gesuchter Wert C', { exact: true }).fill('5')
  await expect(page.getByTestId('result-result')).toHaveText('20')

  await chooseCalculator(page, 'pythagoras', 'Pythagoras')
  await page.getByLabel('Kathete a', { exact: true }).fill('3')
  await page.getByLabel('Kathete b', { exact: true }).fill('4')
  await expect(page.getByTestId('result-c')).toHaveText('5')
  await chooseCalculator(page, 'circle', 'Kreis')
  await page.getByLabel('Radius', { exact: true }).fill('3')
  await expect(page.getByTestId('result-circumference')).toHaveText('18,8495559215')
  await page.goBack()
  await expect(page).toHaveURL(/calculator=pythagoras$/)
  await expect(page.getByLabel('Kathete a', { exact: true })).toHaveValue('3')
  await expect(page.getByTestId('result-c')).toHaveText('5')
  await page.goForward()
  await expect(page.getByLabel('Radius', { exact: true })).toHaveValue('3')

  await chooseCalculator(page, 'area', 'Flächen')
  await page.getByRole('combobox', { name: 'Form', exact: true }).selectOption('triangle')
  await page.getByLabel('Grundseite', { exact: true }).fill('4')
  await page.getByLabel('Höhe', { exact: true }).fill('3')
  await expect(page.getByTestId('result-area')).toHaveText('6 Quadrateinheiten')
  await chooseCalculator(page, 'volume', 'Volumen')
  await page.getByLabel('Breite', { exact: true }).fill('4')
  await page.getByLabel('Tiefe', { exact: true }).fill('5')
  await page.getByLabel('Höhe', { exact: true }).fill('3')
  await expect(page.getByTestId('result-volume')).toHaveText('60 Kubikeinheiten')

  await chooseCalculator(page, 'units', 'Einheiten')
  await page.getByRole('combobox', { name: 'Grösse', exact: true }).selectOption('temperature')
  await page.getByLabel('Wert', { exact: true }).fill('100')
  await expect(page.getByTestId('result-result')).toHaveText('212 °F')
  await page.getByLabel('Wert', { exact: true }).fill('-300')
  await expect(page.getByLabel('Wert', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByTestId('result-result')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Grösse', exact: true }).selectOption('storage')
  await page.getByRole('combobox', { name: 'Von', exact: true }).selectOption('MiB')
  await page.getByRole('combobox', { name: 'Nach', exact: true }).selectOption('B')
  await page.getByLabel('Wert', { exact: true }).fill('1')
  await expect(page.getByTestId('result-result')).toHaveText('1048576 B')
})

test('calculators support keyboard input, mobile layout, and both languages and themes @matrix', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/calculate')
  await expect(page.getByRole('heading', { level: 1, name: 'Rechner' })).toBeVisible()
  const rate = page.getByRole('textbox', { name: 'Prozentsatz', exact: true })
  await rate.focus()
  await page.keyboard.type('20')
  await page.keyboard.press('Tab')
  await expect(page.getByRole('textbox', { name: 'Grundwert', exact: true })).toBeFocused()
  await page.keyboard.type('150')
  await expect(page.getByTestId('result-result')).toHaveText('30')
  const violations = []
  for (const locale of ['de', 'en']) {
    if (locale === 'en') await page.getByRole('button', { name: 'English', exact: true }).click()
    await expect(page.getByRole('heading', { level: 1, name: locale === 'de' ? 'Rechner' : 'Calculators' })).toBeVisible()
    for (const theme of ['light', 'dark']) {
      const toggle = page.locator('.theme-button')
      if (await toggle.getAttribute('aria-pressed') !== String(theme === 'dark')) await toggle.click()
      await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
      await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))))
      const result = await new AxeBuilder({ page }).analyze()
      if (result.violations.length) violations.push({ locale, theme, violations: result.violations })
      expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
    }
  }
  expect(violations).toEqual([])
  await expect(page.getByRole('textbox', { name: 'Base value', exact: true })).toHaveValue('150')
  await expect(page.getByTestId('result-result')).toHaveText('30')
})
