export default {
 title:'Audio zuschneiden',intro:'Bereich auswählen, Ein- und Ausblenden einstellen und als Audiodatei speichern.',
 choose:'Audio auswählen',limits:'MP3, WAV, FLAC oder OGG/Vorbis · bis 100 MiB und 30 Minuten.',
 empty:'Wähle eine Audiodatei, um die Wellenform zu sehen.',preparing:'Wellenform und Vorschau werden vorbereitet …',exporting:'Audiodatei wird erstellt …',cancel:'Abbrechen',reset:'Zurücksetzen',
 waveform:'Wellenform',waveHelp:'Ziehe die Auswahlgrenzen oder gib Start und Ende unten ein. Pfeiltasten verschieben die Grenze um 0.01 Sekunden, mit Umschalttaste um 0.1 Sekunden.',
 start:'Start (Sekunden)',end:'Ende (Sekunden)',startHandle:'Auswahlstart',endHandle:'Auswahlende',fadeIn:'Einblenden (Sekunden)',fadeOut:'Ausblenden (Sekunden)',
 selection:'Auswahl: {duration} s',whole:'Ganze Datei',zoom:'Auswahl vergrössern',unzoom:'Ganze Wellenform',undo:'Rückgängig',redo:'Wiederholen',play:'Auswahl abspielen',pause:'Pausieren',format:'Ausgabeformat',bitrate:'MP3-Bitrate',export:'Audio exportieren',download:'Audiodatei herunterladen',ready:'Audiodatei ist bereit.',local:'Fades zusammen höchstens so lang wie die Auswahl.',
 errors:{playback_unavailable:'Dieser Browser kann die Audiovorschau nicht abspielen. Der Export ist weiterhin möglich.',invalid_file:'Die Audiodatei konnte nicht gelesen werden.',too_large:'Die Datei ist grösser als 100 MiB.',resource_limit:'Die Verarbeitung überschreitet ein Ressourcenlimit oder die Audiodatei ist unvollständig. Wähle eine kürzere Datei oder einen kleineren Bereich.',unsupported_type:'Wähle MP3, WAV, FLAC oder OGG/Vorbis.',type_mismatch:'Dateiendung, Inhalt und Dateityp stimmen nicht überein.',unsupported_codec:'Dieser Audiocodec wird nicht unterstützt. OGG muss Vorbis enthalten.',no_audio:'Die Datei enthält keine unterstützte Audiospur.',invalid_settings:'Prüfe Start, Ende und Fade-Längen.',conversion_failed:'Die Audiodatei konnte nicht verarbeitet werden.',media_runtime_unavailable:'Die Audiolaufzeit fehlt. Verbinde dich mit dem Internet und versuche es erneut. Nach erfolgreicher Nutzung ist sie im Browsercache offline verfügbar.',cancelled:'Verarbeitung abgebrochen.',playback:'Die Vorschau konnte nicht abgespielt werden.'}
}
