const blocks={
 de:{profile:[['focused','Klarer Fokus','[Berufsbezeichnung] mit Erfahrung in [Bereich]. Ich verbinde [Stärke] mit [Stärke] und entwickle [Nutzen für das Unternehmen].'],['career','Beruflicher Wechsel','Nach [Erfahrung] möchte ich meine Kenntnisse in [Zielbereich] einbringen. Besonders motiviert mich [konkreter Bezug zur Stelle].']],experience:[['impact','Messbare Wirkung','• [Massnahme] umgesetzt und dadurch [Ergebnis] um [Zahl] verbessert.'],['ownership','Verantwortung','• Verantwortung für [Aufgabe] übernommen und mit [Teams] erfolgreich umgesetzt.'],['delivery','Projektleistung','• [Projekt] von [Ausgangslage] bis [Ergebnis] begleitet.']],letter:[['opening','Persönlicher Einstieg','Die ausgeschriebene Position als [Position] verbindet [Aufgabe] mit [Aufgabe]. Genau hier möchte ich meine Erfahrung in [Bereich] bei [Unternehmen] einbringen.'],['proof','Konkrete Erfahrung','Bei [Arbeitgeber] habe ich [Aufgabe] verantwortet. Durch [Massnahme] konnte ich [Ergebnis] erreichen. Diese Erfahrung passt zu Ihrem Bedarf an [Anforderung].'],['closing','Abschluss','Gerne zeige ich Ihnen in einem persönlichen Gespräch, wie ich [Unternehmen] bei [Ziel] unterstützen kann. Ich freue mich auf Ihre Rückmeldung.']]},
 en:{profile:[['focused','Clear focus','[Job title] with experience in [field]. I combine [strength] with [strength] to deliver [benefit for the company].'],['career','Career change','After [experience], I want to contribute my skills in [target field]. I am particularly motivated by [specific connection to the role].']],experience:[['impact','Measurable impact','• Implemented [action] and improved [result] by [number].'],['ownership','Ownership','• Took responsibility for [task] and delivered it with [teams].'],['delivery','Project delivery','• Led [project] from [starting point] to [result].']],letter:[['opening','Personal opening','The role of [position] combines [task] with [task]. I would like to contribute my experience in [field] to [company].'],['proof','Concrete experience','At [employer], I was responsible for [task]. By [action], I achieved [result]. This experience aligns with your need for [requirement].'],['closing','Closing paragraph','I look forward to discussing how I can support [company] in achieving [goal]. Thank you for considering my application.']]}}
export function getApplicationTextBlocks(locale,target){return (blocks[locale==='en'?'en':'de'][target]||blocks[locale==='en'?'en':'de'].experience).map(([id,label,text])=>({id,label,text}))}
export function checkApplicationProject(p,jobText=''){
 const issues=[]
 if(!p.person.name.trim())issues.push({code:'missingName',target:'person'})
 if(!p.person.email.trim())issues.push({code:'missingEmail',target:'person'})
 if(!p.letter.subject.trim())issues.push({code:'missingSubject',target:'letter'})
 if(!p.letter.paragraphs.some(x=>x.text.trim()))issues.push({code:'missingBody',target:'letter'})
 const content=[...Object.values(p.person),...p.resume.sections.filter(s=>s.visible).flatMap(s=>[s.title,...s.entries.filter(e=>e.visible).flatMap(e=>[e.title,e.organization,e.description])]),p.letter.subject,...p.letter.paragraphs.map(p=>p.text)].join(' ')
 if(/\[[^\]]+\]/.test(content))issues.push({code:'placeholder',target:'content'})
 const words=[...new Set(jobText.toLowerCase().match(/[\p{L}\p{N}+#.-]{4,}/gu)||[])].slice(0,60)
 return {issues,keywords:words.map(word=>({word,found:content.toLowerCase().includes(word)}))}
}
